server:
  port: 10000
  
#JDBC dataSource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/iyp?serverTimezone=UTC&characterEncoding=UTF-8
    username: yeon
    password: 1111
